### ISSUE TITLE
using json or yaml format for patterns 

### ISSUE THREAD

**Issue by hbakhtiyor** [spectresearch/detectem#2]
great tool, how about using json or yaml format instead of plain python file?
also using ready wappalyzer patterns for the project

**Comment by csalazar** [comment]
Hi @hbakhtiyor, I've decided to use python files because it's easier to add complex logic to the plugins and better in the long term. Many people doing pull requests on the same file (referencing `apps.json` in Wappalyzer) involves resolving merge conflicts and it's a pain eventually for the developer that just wants to contribute quickly. If you care about boilerplate, there's a script that creates the template for the plugin and its test, and we try to group related plugins i.e. the jQuery family lies in the same python file. 

As you can see, plugins like `news-show-pro-gk5` start to use a new feature called `hints` that are functions (in this case a simple one) and *detectem* supports that `matchers` could be regular expressions or functions. In the end, we're not using python files to match only regular expressions.

Migrating Wappalyzer patterns to the project isn't automatic since we need tests to assure the plugin reliability. You can read the documentation on how to contribute with new plugins.

**Comment by hbakhtiyor** [comment]
Hi @csalazar, i see, but need for contributors easy to contribute, and also import from existing datasets (e.g. wappalyzer, ....)

I looked at the plugins, but found very few

**Comment by csalazar** [comment]
Yes, I add plugins slowly according to my requirements but to make the project useful for anyone it needs a community effort.
